Repository osu-capstone-cs72/cs-applied-plan-portal, pull requests merged in 2020-01, with the labels that each got.

#5 Add final versions of documents from Fall 2019
  docs/Design-Document.pdf
  docs/Problem-Statement.pdf
  docs/Progress-Report-Fall-2019.pdf
  docs/Requirements-Document.pdf
Labels: documentation

#9 Fix ESLint not recognize browser's globals
  .eslintrc.json
Labels: bug

#6 Plan submit
  .gitignore
  api/plans.js
  docs/Team-Standards.pdf
  lib/mySqlConn.js
  lib/validation.js
  models/plan.js
  models/user.js
  other/test_db.sql
  package-lock.json
  package.json
  public/index.html
  public/index.js
  public/style.css
  server.js
Labels: enhancement

#10 Add Rob to the license
  LICENSE
Labels: documentation

#13 Require 1 additional indentation in switch-case
  .eslintrc.json
Labels: bug

#11 Organize structure
  .gitattributes
  api/comment.js
  api/course.js
  api/index.js
  api/plan.js
  api/plans.js
  api/user.js
  lib/mySqlConn.js
  lib/validation.js
  models/comment.js
  models/course.js
  models/plan.js
  models/user.js
  server.js
  utils/format.js
  utils/mysqlPool.js
  utils/validation.js
  views/public/index.html
  views/public/index.js
  views/public/style.css
Labels: enhancement

#16 Finish API specs
  docs/openapi.yaml
Labels: documentation
