Repository osu-capstone-cs72/cs-applied-plan-portal, pull requests merged in 2020-04, with the labels that each got.

#70 Security
  api/comment.js
  api/index.js
  api/plan.js
  api/review.js
  api/user.js
  client/package-lock.json
  client/package.json
  client/src/components/Home.js
  client/src/components/Login.js
  client/src/components/advisor_home/AdvisorHome.js
  client/src/components/create_plan/Course.js
  client/src/components/create_plan/CourseContainer.js
  client/src/components/create_plan/EditPlan.js
  client/src/components/create_plan/PlanCourse.js
  client/src/components/create_plan/StudentCreatePlan.js
  client/src/components/manage_roles/ManageRoles.js
  client/src/components/manage_roles/SelectRole.js
  client/src/components/navbar/History.js
  client/src/components/navbar/Logout.js
  client/src/components/navbar/Navbar.js
  client/src/components/navbar/Notifications.js
  client/src/components/navbar/UpdateCourses.js
  client/src/components/student_home/StudentHome.js
  client/src/components/view_plan/CreateComment.js
  client/src/components/view_plan/CreateReview.js
  client/src/components/view_plan/ListSimilarPlans.js
  client/src/components/view_plan/PlanMetadata.js
  client/src/components/view_plan/PlanTable.js
  client/src/components/view_plan/ViewPlan.js
  client/src/utils/authService.js
  client/src/utils/formatTime.js
  package-lock.json
  package.json
  services/auth/auth.js
  services/db/db-init.sql
  services/validation/commentConstraints.js
  services/validation/commentValidation.js
  services/validation/planConstraints.js
  services/validation/planValidation.js
  services/validation/reviewConstraints.js
  services/validation/reviewValidation.js
Labels: bug, feature, priority-0, refactor

#72 Add an installation script and update README
  README.md
  client/README.md
  install.sh
Labels: documentation

#75 Implement styled table placeholders
  client/src/components/App.js
  client/src/components/create_plan/Course.js
  client/src/components/create_plan/CourseContainer.js
  client/src/components/create_plan/EditPlan.js
  client/src/components/general/ErrorMessage.js
  client/src/components/student_home/StudentHome.js
  client/src/components/view_plan/CreateComment.js
  client/src/components/view_plan/PlanMetadata.js
  client/src/components/view_plan/PlanTable.js
Labels: feature

#77 Rewrite edit plan page with nested grids
  client/src/components/create_plan/Course.js
  client/src/components/create_plan/CourseSearch.js
  client/src/components/create_plan/EditPlan.js
  client/src/components/create_plan/EditPlanTable.js
  client/src/components/create_plan/PlanCourse.js
  client/src/components/create_plan/StudentCreatePlan.js
  client/src/components/navbar/Navbar.js
  client/src/components/student_home/StudentHome.js
  client/src/components/view_plan/PlanMetadata.js
  client/src/components/view_plan/PlanTable.js
Labels: feature, refactor

#79 Requirements testing
  docs/Requirements-ChangeLog.pdf
  docs/Requirements-Document.pdf
  services/db/db-init.sql
Labels: documentation

#81 Change npm script and server imports according to environment
  README.md
  api/index.js
  package.json
  server.js
  services/auth/auth.js
Labels: deployment

#82 Fix faulty npm install prefix on Windows
  install.sh
Labels: bug

#83 Unit tests back end
  README.md
  __tests__/Plan.test.js
  api/course.js
  api/index.js
  api/notification.js
  api/plan.js
  api/review.js
  api/user.js
  client/package-lock.json
  client/package.json
  client/src/__tests__/StudentCreatePlan.test.js
  client/src/__tests__/StudentHome.test.js
  client/src/__tests__/__snapshots__/StudentHome.test.js.snap
  client/src/utils/cookieInfo.js
  client/src/utils/formatRole.js
  package-lock.json
  package.json
  services/auth/auth.js
  services/validation/commentConstraints.js
  services/validation/commentValidation.js
  services/validation/planConstraints.js
  services/validation/planValidation.js
  services/validation/reviewConstraints.js
  services/validation/reviewValidation.js
Labels: testing
