Repository osu-capstone-cs72/cs-applied-plan-portal, pull requests merged in 2020-05, with the labels that each got.

#85 Update the API specs to match with current endpoints
  docs/openapi.yaml
Labels: documentation

#86 Bug fixes
  client/src/__tests__/Navbar.test.js
  client/src/components/advisor_home/AdvisorHome.js
  client/src/components/create_plan/Course.js
  client/src/components/create_plan/StudentCreatePlan.js
  client/src/components/manage_roles/ManageRoles.js
  client/src/components/navbar/History.js
  client/src/components/navbar/Navbar.js
  client/src/components/student_home/StudentHome.js
  client/src/components/view_plan/ViewPlan.js
  services/db/db-init.sql
Labels: bug, refactor

#88 Deploy on Heroku with main instance of CAS
  .gitignore
  README.md
  api/index.js
  api/user.js
  client/src/components/student_home/StudentHome.js
  client/src/utils/authService.js
  client/src/utils/environment.js
  entities/environment.js
  package.json
  server.js
  services/auth/auth.js
  services/db/mysqlPool.js
Labels: deployment, refactor

#89 Code Review Updates
  README.md
  client/src/__tests__/StudentCreatePlan.test.js
  client/src/__tests__/StudentHome.test.js
  client/src/components/App.js
  client/src/components/Home.js
  client/src/components/Login.js
  client/src/components/advisor_home/AdvisorHome.js
  client/src/components/advisor_home/FindPlans.js
  client/src/components/advisor_home/SearchResults.js
  client/src/components/create_plan/Course.js
  client/src/components/create_plan/CourseSearch.js
  client/src/components/create_plan/EditPlan.js
  client/src/components/create_plan/EditPlanTable.js
  client/src/components/create_plan/FilterBar.js
  client/src/components/create_plan/PlanCourse.js
  client/src/components/create_plan/StudentCreatePlan.js
  client/src/components/general/ErrorMessage.js
  client/src/components/general/LoadMoreButton.js
  client/src/components/general/PageInternalError.js
  client/src/components/general/PageNotFound.js
  client/src/components/general/PageSpinner.js
  client/src/components/manage_roles/FindUsers.js
  client/src/components/manage_roles/ManageRoles.js
  client/src/components/manage_roles/SearchResults.js
  client/src/components/manage_roles/SelectRole.js
  client/src/components/navbar/History.js
  client/src/components/navbar/Logout.js
  client/src/components/navbar/Navbar.js
  client/src/components/navbar/Notifications.js
  client/src/components/navbar/UpdateCourses.js
  client/src/components/student_home/Advisor.js
  client/src/components/student_home/StatusCue.js
  client/src/components/student_home/StudentHome.js
  client/src/components/view_plan/ActivityFeed.js
  client/src/components/view_plan/Comment.js
  client/src/components/view_plan/CreateComment.js
  client/src/components/view_plan/CreateReview.js
  client/src/components/view_plan/ListSimilarPlans.js
  client/src/components/view_plan/PlanMetadata.js
  client/src/components/view_plan/PlanTable.js
  client/src/components/view_plan/Review.js
  client/src/components/view_plan/ViewPlan.js
  client/src/utils/cookieInfo.js
  docs/Code_Review_Actions.pdf
  package.json
Labels: documentation, refactor

#90 Fix issue
  api/course.js
Labels: bug

#91 Make file names consistent and update README.md
  README.md
  docs/Code-Review-Actions.pdf
  docs/End-of-Term-Report-Fall-2019.pdf
  docs/End-of-Term-Report-Winter-2020.pdf
  docs/Requirements-Document-ChangeLog.pdf
Labels: documentation
